package com.eric.lab2;

import java.util.Scanner;

/**
 * @author Eric Strong Date: 8 Feb 2017 Lab: ID: C15708709
 */
public class ControlApp
{
	public static int size = 2;
	public static Employee myEmployees[] = new Employee[size];

	public static void main(String[] args)
	{

		// create objects

		Employee e1 = new Employee("Eric", "Strong", 1, 25000.50, "08/02/2017"); // employee
																					// object
		HourlyEmployee he1 = new HourlyEmployee("Ger", "Strong", 2, 0.00, "09/02/2017", 40, 10.50); // hourlyEmployee
																									// object

		CommissionEmployee ce1 = new CommissionEmployee("Margaret", "Strong", 3, 25000.50, "10/02/2017", 550.50); // employee
																													// object
		// print out each object
		System.out.println(e1);
		System.out.println(he1);
		System.out.println(ce1);

		// PART 3 - it's mighty polymorphism time
		generateEmployeesDetails();

		// print all elements of the array
		for (int i = 0; i < myEmployees.length; i++)
		{
			System.out.println(myEmployees[i]);
		}

	}// end main Method

	public static void generateEmployeesDetails()
	{

		Scanner scan = new Scanner(System.in);

		for (int i = 0; i < myEmployees.length; i++)
		{
			System.out.println("enter your first name:");
			String fname = scan.next();
			System.out.println("enter your surname:");
			String sName = scan.next();
			// employee number will be generated by the loop
			System.out.println("enter your start date: (DD/MM/YYYY)");
			String startDate = scan.next();

			if (i % 2 == 0)
			{
				// create object
				Employee em1 = new Employee(fname, sName, (i + 1), (100.00 + i), startDate);
				myEmployees[i] = em1;
			} else if (i % 2 == 1)
			{
				// create object
				Employee em1 = new Employee(fname, sName, (i + 1), (100.00 + i), startDate);
				myEmployees[i] = em1;
			}

		} // end for loop

		// close the scanner object
		scan.close();

	}// end generateEmployeesDetails

}// end ControlApp
